#spring.application.name=WeatherServer
#serverTimezone=UTC&
server:
  port: 8085
spring:
  application:
    name: WeatherServer
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdata_db?useSSL=false&characterEncoding=utf8
    username: root
    password: (h/n)Nmdv7-d
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true