#spring.application.name=WeatherServer
#serverTimezone=UTC&
server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:D:/!Java/weatherserver/src/main/resources/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myserver
    key-password: 123456

spring:
  application:
    name: WeatherServer
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdata_db?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: (h/n)Nmdv7-d
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true